import Head from 'next/head'
import Image from 'next/image'
import Avatar from '../components/Avatar'
import styles from '../styles/Home.module.css'
import AppsIcon from '@mui/icons-material/Apps';
import SearchIcon from '@mui/icons-material/Search';
import KeyboardVoiceIcon from '@mui/icons-material/KeyboardVoice';
import Footer from '../components/Footer';
import { useRef } from 'react';
import Router, { useRouter } from 'next/router';

export default function Home() {


  const InputRef = useRef(null)

  const search = (e) => {

    e.preventDefault()
    //Retrieve Value from Input
    const inputData = InputRef.current.value
    console.log(inputData)
    
    //If no data return nothing
    if (!inputData) return;

    Router.push(`/search?q=${inputData}`)

    //On Click clear the value
    InputRef.current.value = null

  }

  return (
    <div className=' flex flex-col  h-screen justify-between'>
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <header className='flex justify-between items-center w-full  '>
        <div className=' flex space-x-4 p-4 font-medium text-gray-700 items-center'>
          <p>About</p>
          <p>Store</p>
        </div>
        <div className=' flex space-x-4 p-4 font-medium text-gray-700 items-center'>
          <p>Gmail</p>
          <p>Images</p>
          <AppsIcon className='h-10 w-10 rounded-full p-2 hover:bg-gray-100  cursor-pointer' />
          <Avatar url="https://avatarairlines.com/wp-content/uploads/2020/05/Male-placeholder.jpeg" />
        </div>
      </header>


      {/* Body */}
      <form className='flex flex-col items-center' >
        <Image src='https://www.logo.wine/a/logo/Google_Search/Google_Search-Logo.wine.svg' width={450} height={200} />
        <div className=' w-full p-4 border-solid border-2  rounded-full flex hover:shadow-lg focus-within:bg-gray-100 max-w-md md:max-w-2xl' >
          <SearchIcon className=' text-gray-500' />
          <input ref={InputRef} className='w-full outline-none focus-within:bg-gray-100 ml-1' />
          <KeyboardVoiceIcon />
        </div>
        <div className='flex  mt-6 flex-col items-center space-y-4 md:flex-row md:space-y-0 md:space-x-4'>
          <button className=' bg-gray-100 pl-4 pr-4 pt-2 pb-2 rounded-sm text-gray-700 hover:ring-1 ring-gray-200' onClick={search}>Google Search</button>
          <button className=' bg-gray-100 pl-4 pr-4 pt-2 pb-2 rounded-sm text-gray-700  hover:ring-1 ring-gray-200'> I'm Feeling Lucky</button>
        </div>
      </form>




      {/* Footer */}
      <Footer />

    </div>
  )
}
