import React, { useRef, useEffect, useState } from 'react'
import Image from 'next/image'
import SearchIcon from '@mui/icons-material/Search';
import MicIcon from '@mui/icons-material/Mic';
import SettingsIcon from '@mui/icons-material/Settings';
import AppsIcon from '@mui/icons-material/Apps';
import Avatar from '../components/Avatar';
import HeaderLinks from '../components/HeaderLinks';
import CloseIcon from '@mui/icons-material/Close';
import Router, { useRouter } from 'next/router';
import Head from 'next/head'
import { API_KEY, CONTEXT_KEY } from '../key';
const search = () => {

  const displayRef = useRef(null)
  const router = useRouter()
  const inputData = router?.query.q
  console.log(inputData)
  const [isFocused, setFocused] = useState(false)

  return (


    <header className='w-full min-w-[1138px] border-b-2 border-solid border-gray-200 pt-8 pl-3 pr-5 '>

      <Head>
        <title>{`Google | search ${router.query.q}`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      {/* TOP HEADER */}
      <div className='flex  justify-between pb-3 '>

        {/* HeaderLeft */}
        <div className='flex space-x-8 w-full flex-grow'>
          <Image src='https://www.logo.wine/a/logo/Google_Search/Google_Search-Logo.wine.svg' width={150} height={60} onClick={ ()=> Router.push('/')} className=' cursor-pointer'/>
          <div className=' flex items-center border-solid  rounded-full  shadow-lg border-gray-100 p-3  border-2 space-x-4 flex-grow max-w-lg md:max-w-xl 2xl:max-w-3xl ' >
            {isFocused && <SearchIcon />}
            <input className=' outline-none ml-2  w-full ' onFocus={() => setFocused(true)} ref={displayRef} onBlur={() => setFocused(false)} value={inputData} />
            <CloseIcon className='text-gray-600 border-r-2  pr-1 w-8 ' />

            <MicIcon className=' text-blue-500 text-2xl' />
            <SearchIcon className=' text-blue-500 text-2xl' />
          </div>
        </div>

        {/* Header Right */}
        <div className='flex items-center space-x-6 text-gray-600 pr-8'>
          <SettingsIcon />
          <AppsIcon />
          <Avatar url="https://avatarairlines.com/wp-content/uploads/2020/05/Male-placeholder.jpeg" />
        </div>
      </div>

      {/* Header Links */}
      <HeaderLinks />










    </header>
  )
}

export default search




export async function getServerSideProps(context) {
  const useDummyData = false;
  // Fetch data from external API
  const { term } = context.query;
  const res = await fetch(`https://www.googleapis.com/customsearch/v1?key=${API_KEY}&cx=${CONTEXT_KEY}&q=${term}`)
  const data = await res.json()
  
  console.log(data)
  // Pass data to the page via props
  return { props: { data } }
}